# Generated by Django 5.1.5 on 2025-01-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_bmirecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='bmi_category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
