# Generated by Django 5.1.5 on 2025-01-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_bmirecord_bmi_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=30, max_length=1),
            preserve_default=False,
        ),
    ]
