# Generated by Django 5.1.5 on 2025-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_bmirecord_age_bmirecord_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='activity_level',
            field=models.CharField(choices=[('S', 'Sedentary'), ('LA', 'Lightly Active'), ('MA', 'Moderately Active'), ('VA', 'Very Active')], default='S', max_length=2),
        ),
    ]
