# Generated by Django 5.1.5 on 2025-01-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_bmirecord_activity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmirecord',
            name='activity_level',
        ),
    ]
